name: 'Downgrade code'
description: 'Downgrade code'
inputs:
  php-version:
    description: 'Original PHP version'
    required: true
runs:
  using: "composite"
  steps:

    - name: "Change to simple-downgrade PHP version"
      if: inputs.php-version == '7.4' || inputs.php-version == '8.0' || inputs.php-version == '8.1'
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "8.4"

    - name: "Transform source code"
      if: inputs.php-version == '7.4' || inputs.php-version == '8.0' || inputs.php-version == '8.1'
      shell: bash
      run: |
        composer install --no-interaction --no-progress --working-dir=compiler
        ./compiler/vendor/bin/simple-downgrade downgrade -c build/downgrade.php ${{ inputs.php-version }}
        composer dump

    - name: "Re-store PHP version"
      if: inputs.php-version == '7.4' || inputs.php-version == '8.0' || inputs.php-version == '8.1'
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "${{ inputs.php-version }}"
        ini-file: development
        extensions: ds,mbstring
